---

- hosts: all
  become: true
  tasks:

  - name:  install apache2 and php for ubuntu servers
    apt:
      name:
        - apache
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name:  install httpd and php for amazon linux 2023 servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Amazon"


